[package]
name = "compilador-de-calculos"
version = "0.1.0"
authors = ["Thiago Romano <thiagopromano@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
crossterm = "0.17.5"